{
 "cells": [
  {
   "source": [
    "## BiLSTM for MIT Movies"
   ],
   "cell_type": "markdown",
   "metadata": {}
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import sys\n",
    "import json\n",
    "import numpy as np\n",
    "from tqdm import tqdm\n",
    "sys.path.append(\"..\")\n",
    "\n",
    "from torch import nn\n",
    "from torch.optim import Adam\n",
    "from src.movientities.models.lstm import BiLSTM\n",
    "from src.movientities.trainers import TrainerBiLstm\n",
    "from src.movientities.utils.processors import NerPreProcessor\n",
    "from src.movientities.data.build_dataset import Corpus, BuildData"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "output_type": "stream",
     "name": "stderr",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3437, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-6-bab92a44302a>\", line 1, in <module>\n",
      "    absolute_path = [path for path in globals()['_dh'] if \"NamedEntity\" in path.split(os.sep)][0]\n",
      "IndexError: list index out of range\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2061, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'IndexError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/inspect.py\", line 1502, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/inspect.py\", line 1460, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/inspect.py\", line 725, in getmodule\n",
      "    file = getabsfile(object, _filename)\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/inspect.py\", line 709, in getabsfile\n",
      "    return os.path.normcase(os.path.abspath(_filename))\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/posixpath.py\", line 383, in abspath\n",
      "    cwd = os.getcwd()\n",
      "FileNotFoundError: [Errno 2] No such file or directory\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3437, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-6-bab92a44302a>\", line 1, in <module>\n",
      "    absolute_path = [path for path in globals()['_dh'] if \"NamedEntity\" in path.split(os.sep)][0]\n",
      "IndexError: list index out of range\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2061, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'IndexError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3357, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3454, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2064, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1368, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1268, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1125, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2061, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/inspect.py\", line 1502, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/inspect.py\", line 1460, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/inspect.py\", line 725, in getmodule\n",
      "    file = getabsfile(object, _filename)\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/inspect.py\", line 709, in getabsfile\n",
      "    return os.path.normcase(os.path.abspath(_filename))\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/posixpath.py\", line 383, in abspath\n",
      "    cwd = os.getcwd()\n",
      "FileNotFoundError: [Errno 2] No such file or directory\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3437, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-6-bab92a44302a>\", line 1, in <module>\n",
      "    absolute_path = [path for path in globals()['_dh'] if \"NamedEntity\" in path.split(os.sep)][0]\n",
      "IndexError: list index out of range\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2061, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'IndexError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3357, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3454, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2064, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1368, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1268, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1125, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2061, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2940, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/site-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3166, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3376, in run_ast_nodes\n",
      "    self.showtraceback()\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2064, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1368, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1268, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1143, in structured_traceback\n",
      "    chained_exceptions_tb_offset)\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2061, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/inspect.py\", line 1502, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/inspect.py\", line 1460, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/inspect.py\", line 725, in getmodule\n",
      "    file = getabsfile(object, _filename)\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/inspect.py\", line 709, in getabsfile\n",
      "    return os.path.normcase(os.path.abspath(_filename))\n",
      "  File \"/home/karaz/anaconda3/envs/project/lib/python3.7/posixpath.py\", line 383, in abspath\n",
      "    cwd = os.getcwd()\n",
      "FileNotFoundError: [Errno 2] No such file or directory\n"
     ]
    }
   ],
   "source": [
    "# For finding the absolute path dynamically for every other user for the sake of this notebooks paths\n",
    "for path in globals()['_dh']:\n",
    "    if \"NamedEntityRecognizer\" in path.split(os.sep):\n",
    "        absolute_path = os.path.split(path)[0]\n",
    "        break\n",
    "print(absolute_path)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Create datasets with tab as splitter for corpus of torch text to handle - Uncomment if needed -\n",
    "# Convert ->  O\tgood             -> to ->  good     O           \n",
    "# Convert ->  B-GENRE\tromantic -> to ->  romantic B-GENRE\n",
    "# Convert ->  I-GENRE\tcomedies -> to ->  comedies I-GENRE\n",
    "BuildData.create_finaldata(os.path.join(absolute_path, \"data/raw/mitmovies/engtrain.bio\"), os.path.join(absolute_path, \"data/modified/mitmovies_tab_format/train.txt\"), splits=\"\\t\")\n",
    "BuildData.create_finaldata(os.path.join(absolute_path, \"data/raw/mitmovies/engtest.bio\"), os.path.join(absolute_path, \"data/modified/mitmovies_tab_format/test.txt\"), splits=\"\\t\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "output_type": "stream",
     "name": "stdout",
     "text": [
      "Train set: 9775 sentences\nTest set: 2443 sentences\n"
     ]
    }
   ],
   "source": [
    "# Dataset class\n",
    "dataset = Corpus(\n",
    "    input_folder=os.path.join(absolute_path, \"data/modified/mitmovies_tab_format\"),\n",
    "    min_word_freq=3,  # any words occurring less than 3 times will be ignored from vocab\n",
    "    batch_size=64)\n",
    "print(f\"Train set: {len(dataset.train_dataset)} sentences\")\n",
    "print(f\"Test set: {len(dataset.test_dataset)} sentences\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The model has 1,161,930 trainable parameters.\n",
      "BiLSTM(\n",
      "  (embedding): Embedding(2244, 300, padding_idx=1)\n",
      "  (emb_dropout): Dropout(p=0.25, inplace=False)\n",
      "  (lstm): LSTM(300, 64, num_layers=4, dropout=0.01, bidirectional=True)\n",
      "  (fc_dropout): Dropout(p=0.1, inplace=False)\n",
      "  (fc): Linear(in_features=128, out_features=26, bias=True)\n",
      ")\n"
     ]
    }
   ],
   "source": [
    "model = BiLSTM(\n",
    "    input_dim=len(dataset.word_field.vocab),\n",
    "    embedding_dim=300,\n",
    "    hidden_dim=64,\n",
    "    output_dim=len(dataset.tag_field.vocab),\n",
    "    lstm_layers=4,\n",
    "    emb_dropout=0.25,\n",
    "    lstm_dropout=0.01,\n",
    "    fc_dropout=0.1,\n",
    "    word_pad_idx=dataset.word_pad_idx,\n",
    ")\n",
    "# Initialize weights and embeddings\n",
    "model.init_weights()\n",
    "model.init_embeddings(word_pad_idx=dataset.word_pad_idx)\n",
    "print(f\"The model has {model.count_parameters():,} trainable parameters.\")\n",
    "print(model)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch: 01 | Epoch Time: 0m 22s\n",
      "\tTrn Loss: 0.903 | Trn Acc: 75.58%\n",
      "\tVal Loss: 0.763 | Val Acc: 80.36% | Val Precision: 60.83% | Val Recall: 55.18% | Val F1 Macro: 53.84% | Val F1 Micro: 80.28%\n",
      "Epoch: 02 | Epoch Time: 0m 22s\n",
      "\tTrn Loss: 0.448 | Trn Acc: 88.92%\n",
      "\tVal Loss: 0.520 | Val Acc: 87.07% | Val Precision: 74.27% | Val Recall: 72.57% | Val F1 Macro: 70.96% | Val F1 Micro: 86.40%\n",
      "Epoch: 03 | Epoch Time: 0m 22s\n",
      "\tTrn Loss: 0.321 | Trn Acc: 92.06%\n",
      "\tVal Loss: 0.453 | Val Acc: 88.60% | Val Precision: 75.65% | Val Recall: 75.65% | Val F1 Macro: 73.28% | Val F1 Micro: 87.79%\n",
      "Epoch: 04 | Epoch Time: 0m 21s\n",
      "\tTrn Loss: 0.272 | Trn Acc: 93.18%\n",
      "\tVal Loss: 0.432 | Val Acc: 88.86% | Val Precision: 77.34% | Val Recall: 73.99% | Val F1 Macro: 73.20% | Val F1 Micro: 87.94%\n",
      "Epoch: 05 | Epoch Time: 0m 22s\n",
      "\tTrn Loss: 0.238 | Trn Acc: 94.04%\n",
      "\tVal Loss: 0.415 | Val Acc: 89.34% | Val Precision: 74.38% | Val Recall: 74.84% | Val F1 Macro: 72.41% | Val F1 Micro: 88.23%\n",
      "Epoch: 06 | Epoch Time: 0m 21s\n",
      "\tTrn Loss: 0.210 | Trn Acc: 94.56%\n",
      "\tVal Loss: 0.401 | Val Acc: 89.78% | Val Precision: 75.28% | Val Recall: 76.24% | Val F1 Macro: 73.80% | Val F1 Micro: 88.64%\n",
      "Epoch: 07 | Epoch Time: 0m 21s\n",
      "\tTrn Loss: 0.190 | Trn Acc: 95.08%\n",
      "\tVal Loss: 0.394 | Val Acc: 90.34% | Val Precision: 81.01% | Val Recall: 78.57% | Val F1 Macro: 77.77% | Val F1 Micro: 89.26%\n",
      "Epoch: 08 | Epoch Time: 0m 21s\n",
      "\tTrn Loss: 0.174 | Trn Acc: 95.43%\n",
      "\tVal Loss: 0.377 | Val Acc: 90.75% | Val Precision: 79.25% | Val Recall: 78.46% | Val F1 Macro: 77.28% | Val F1 Micro: 89.65%\n",
      "Epoch: 09 | Epoch Time: 0m 21s\n",
      "\tTrn Loss: 0.155 | Trn Acc: 95.88%\n",
      "\tVal Loss: 0.400 | Val Acc: 90.46% | Val Precision: 78.56% | Val Recall: 76.90% | Val F1 Macro: 76.16% | Val F1 Micro: 89.35%\n",
      "Epoch: 10 | Epoch Time: 0m 22s\n",
      "\tTrn Loss: 0.143 | Trn Acc: 96.10%\n",
      "\tVal Loss: 0.423 | Val Acc: 90.14% | Val Precision: 76.37% | Val Recall: 77.53% | Val F1 Macro: 75.20% | Val F1 Micro: 89.04%\n",
      "Epoch: 11 | Epoch Time: 0m 22s\n",
      "\tTrn Loss: 0.134 | Trn Acc: 96.35%\n",
      "\tVal Loss: 0.397 | Val Acc: 90.61% | Val Precision: 78.11% | Val Recall: 78.22% | Val F1 Macro: 76.48% | Val F1 Micro: 89.48%\n",
      "Epoch: 12 | Epoch Time: 0m 23s\n",
      "\tTrn Loss: 0.121 | Trn Acc: 96.70%\n",
      "\tVal Loss: 0.395 | Val Acc: 90.74% | Val Precision: 78.15% | Val Recall: 77.47% | Val F1 Macro: 76.08% | Val F1 Micro: 89.54%\n",
      "Epoch: 13 | Epoch Time: 0m 23s\n",
      "\tTrn Loss: 0.111 | Trn Acc: 96.94%\n",
      "\tVal Loss: 0.430 | Val Acc: 90.54% | Val Precision: 78.11% | Val Recall: 77.00% | Val F1 Macro: 75.97% | Val F1 Micro: 89.39%\n",
      "Epoch: 14 | Epoch Time: 0m 23s\n",
      "\tTrn Loss: 0.102 | Trn Acc: 97.15%\n",
      "\tVal Loss: 0.401 | Val Acc: 90.83% | Val Precision: 75.97% | Val Recall: 76.71% | Val F1 Macro: 74.92% | Val F1 Micro: 89.56%\n",
      "Epoch: 15 | Epoch Time: 0m 24s\n",
      "\tTrn Loss: 0.094 | Trn Acc: 97.32%\n",
      "\tVal Loss: 0.409 | Val Acc: 91.04% | Val Precision: 78.06% | Val Recall: 77.96% | Val F1 Macro: 76.53% | Val F1 Micro: 89.87%\n",
      "Epoch: 16 | Epoch Time: 0m 24s\n",
      "\tTrn Loss: 0.087 | Trn Acc: 97.55%\n",
      "\tVal Loss: 0.423 | Val Acc: 90.80% | Val Precision: 79.64% | Val Recall: 76.99% | Val F1 Macro: 76.63% | Val F1 Micro: 89.62%\n",
      "Epoch: 17 | Epoch Time: 0m 23s\n",
      "\tTrn Loss: 0.081 | Trn Acc: 97.65%\n",
      "\tVal Loss: 0.427 | Val Acc: 90.82% | Val Precision: 79.41% | Val Recall: 77.24% | Val F1 Macro: 76.55% | Val F1 Micro: 89.63%\n",
      "Epoch: 18 | Epoch Time: 0m 24s\n",
      "\tTrn Loss: 0.073 | Trn Acc: 97.85%\n",
      "\tVal Loss: 0.442 | Val Acc: 90.83% | Val Precision: 78.28% | Val Recall: 78.13% | Val F1 Macro: 76.66% | Val F1 Micro: 89.64%\n",
      "Epoch: 19 | Epoch Time: 0m 23s\n",
      "\tTrn Loss: 0.067 | Trn Acc: 97.98%\n",
      "\tVal Loss: 0.445 | Val Acc: 91.00% | Val Precision: 78.04% | Val Recall: 78.45% | Val F1 Macro: 76.45% | Val F1 Micro: 89.81%\n",
      "Epoch: 20 | Epoch Time: 0m 24s\n",
      "\tTrn Loss: 0.063 | Trn Acc: 98.14%\n",
      "\tVal Loss: 0.453 | Val Acc: 91.21% | Val Precision: 78.82% | Val Recall: 78.45% | Val F1 Macro: 76.99% | Val F1 Micro: 90.01%\n"
     ]
    }
   ],
   "source": [
    "ner = TrainerBiLstm(\n",
    "  model=model,\n",
    "  data=dataset,\n",
    "  optimizer_cls=Adam,\n",
    "  loss_fn_cls=nn.CrossEntropyLoss,\n",
    "  log_name=\"bilstm_vanilla2\"\n",
    ")\n",
    "ner.train(20)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "name": "python3",
   "display_name": "Python 3.7.10 64-bit ('project': conda)",
   "metadata": {
    "interpreter": {
     "hash": "14dbe4d4df743aee721c7bd8dbc75325a1aee7c29f250bc6dc30066efadd3ddb"
    }
   }
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}